name: flutter_ai
description: "A new Flutter project."

publish_to: 'none' # 私有包，防止意外發布到 pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.10
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  image_picker: ^0.8.7+4
  share_plus: ^11.0.0
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
